# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HSLProto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HSLProto
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'HSLProto-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HSLProtoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
